package app;
import java.util.ArrayList;

public class Main { 
	public static Action move = new Action(Action.MOVE);
 	public static Action talk = new Action(Action.NPC);
 	public static Action propose = new Action(Action.PROPOSE);
 	public static Action hint = new Action(Action.HINT);
	public static void main(String[] args){
		
	    // Hints creation
		ArrayList<Hint> hints = new ArrayList<>();
		Hint kratosHint = new Hint("kratosHint","Je porte les cicatrices d'un dieu, armé de lames et hanté par mes erreurs.");
		hints.add(kratosHint);
		Hint spyroHint = new Hint("spyroHint","Je me promène à travers mon monde, toujours accompagné de mon fidèle ami Sparx");
		hints.add(spyroHint);
		Hint crashHint = new Hint("crashHint","Avec Uka Uka, je sauve le mondes des horribles plans de N.Cortex");
		hints.add(crashHint);
		Hint laraCroftHint = new Hint("laraCroftHint","Je plonge dans les temples oubliés, armée de mes pistolets et de mon courage.");
		hints.add(laraCroftHint);
		Hint reginaHint = new Hint("reginaHint","Je me bats contre des créatures préhistoriques dans des laboratoires secrets.");
		hints.add(reginaHint);
		Hint alloyHint = new Hint("alloyHint","Je traque des machines dans un monde post-apocalyptique.");
		hints.add(alloyHint);
		Hint cloudHint = new Hint("cloudHint","Je manie une immense épée dans une lutte pour sauver la planète.");
		hints.add(cloudHint);
		Hint ellieHint = new Hint("ellieHint","Immunisé contre l'infection, je parcours l'Amérique pour vanger mon ami Joël");
		hints.add(ellieHint);
		Hint geraldDeRivHint = new Hint("geraldDeRivHint","Je suis un sorceleur, pourfendeur de monstres et amateur de Gwynt.");
		hints.add(geraldDeRivHint);
		Hint masterChiefHint = new Hint("masterChiefHint","Je suis un super-soldat en armure verte, protecteur de l'humanité.");
		hints.add(masterChiefHint);
		Hint rayneHint = new Hint("rayneHint","Je suis une dhampire qui traque les nazis et les monstres.");
		hints.add(rayneHint);
		Hint blinxHint = new Hint("blinxHint","Je voyage à travers le temps avec un aspirateur magique.");
		hints.add(blinxHint);
		Hint sonicHint = new Hint("sonicHint","Je cours plus vite que le vent, collectionne les anneaux, et combat un docteur maléfique.");
		hints.add(sonicHint);
		Hint doomguyHint = new Hint("doomguyHint","Je suis un marine solitaire qui affronte l'enfer.");
		hints.add(doomguyHint);
		Hint marcusFenixHint = new Hint("marcusFenixHint","Je combats les Locustes avec mon fusil Lancer.");
		hints.add(marcusFenixHint);
		Hint oriHint = new Hint("oriHint","Je suis une lueur fragile qui illumine un monde sombre");
		hints.add(oriHint);
		Hint madelineHint = new Hint("madelineHint","Je suis une jeune femme qui affronte ses propres démons en montagne.");
		hints.add(madelineHint);
		Hint zagreusHint = new Hint("zagreusHint","Je tente de m’échapper des Enfers, soutenu par les dieux de l’Olympe.");
		hints.add(zagreusHint);
		Hint samFicherHint = new Hint("samFicherHint","Je suis un agent secret, armé de mes lunettes à vision nocturne");
		hints.add(samFicherHint);
		Hint marioHint = new Hint("marioHint","Je saute de champignons en champignons à la recherche de ma princesse.");
		hints.add(marioHint);
		Hint linkHint = new Hint("linkHint","Je suis un héros silencieux qui protège Hyrule avec courage.");
		hints.add(linkHint);
		Hint kirbyHint = new Hint("kirbyHint","Je suis une petite boule rose qui aspire tout sur son chemin.");
		hints.add(kirbyHint);
		Hint sachaHint = new Hint("sachaHint","Je voyage avec Pikachu pour capturer et entraîner des Pokémon.");
		hints.add(sachaHint);
		Hint samusAranHint = new Hint("samusAranHint","Je combats des créatures extraterrestres dans une armure puissante.");
		hints.add(samusAranHint);
		Hint donkeyKongHint = new Hint("donkeyKongHint","Je suis un gorille costaud qui adore les bananes.");
		hints.add(donkeyKongHint);
		Hint vladHint = new Hint("vladHint","Je manipule la Psynergie pour sauver Weyard de la destruction.");
		hints.add(vladHint);
		Hint hershelLaytonHint = new Hint("hershelLaytonHint","Je résous des énigmes avec mon fidèle haut de forme et mon assistant Luke.");
		hints.add(hershelLaytonHint);
		
		

	    // Non players characters creation
		ArrayList<Npc> npcs = new ArrayList<>();
		Npc laracroft = new Npc("Lara Croft",laraCroftHint,"Intrigué par ces ruines, voyageur ? Moi aussi.", "Bravo, tu m'as reconnue. Lara Croft, exploratrice de l'inconnu.","Non, c'est un mauvais tir. Mais garde espoir.");
		npcs.add(laracroft);
		Npc masterchief = new Npc("MasterChief",masterChiefHint,"Soldat, restez concentré. La mission est loin d’être terminée.", "Correct. Master Chief, Spartan 117, au rapport.","Non, recalé. Réessayez, marine.");
		npcs.add(masterchief);
		Npc cloud = new Npc("Cloud",cloudHint,"Une lame ne suffit pas. Le courage fait tout.", "C'est moi, Cloud Strife. Mais tu le savais déjà, non ?","Non, ce n'est pas ça. Concentre-toi, comme sur une limite.");
		npcs.add(cloud);
		Npc geraldderiv = new Npc("Gerald de Riv",geraldDeRivHint,"Un autre monstre à chasser, ou peut-être juste un humain curieux ?", "Correct. Je suis Geralt, le Loup Blanc.","Non, une mauvaise piste. Reviens quand tu auras compris l'indice.");
		npcs.add(geraldderiv);
		Npc crashbandicoot = new Npc("CrashBandicoot",crashHint,"Woooaaah! T'a pas des pommes sur toi ?", "Haha, ouais, c'est moi, Crash Bandicoot ! Où sont mes Wumpas?!","Boing boing Non, c'est pas ça ! Essaie encore, ami !");
		npcs.add(crashbandicoot);
		Npc kratos = new Npc("Kratos",kratosHint,"Un voyageur dans mon royaume ? Espère ne pas éveiller ma colère.", "Tu es perspicace. Oui, je suis Kratos, le Fantôme de Sparte.","Non. Ton ignorance ne mérite pas ma pitié.");
		npcs.add(kratos);
		Npc sonic = new Npc("Sonic",sonicHint,"Hé, toi là-bas ! T’arrives à me suivre ou je vais trop vite ?", "Tu as vu juste ! Sonic, le hérisson le plus rapide au monde !","Non, mauvaise réponse ! Allez, accélère un peu !");
		npcs.add(sonic);
		Npc madeline = new Npc("Madeline",madelineHint,"La montagne est rude. Mais toi aussi, non ?", "Oui, je suis Madeline. Je gravis les sommets, à ma façon.","Non, ce n’est pas ça. Mais ne lâche pas prise.");
		npcs.add(madeline);
		Npc ellie = new Npc("Ellie",ellieHint,"Hé, toi ! T’es pas infecté, hein ?", "Bien vu. Ellie, survivante coriace, prête à tout.","Nope. Mauvaise réponse. Essaie encore, cowboy.");
		npcs.add(ellie);
		Npc spyro = new Npc("Spyro",spyroHint,"Hé, petite flamme ! T'as vu d'autres dragons par ici ?", "C'est moi, Spyro, prêt à brûler quelques ennemis !","Non, t'es à côté de la plaque. Essaie encore !");
		npcs.add(spyro);
		Npc thedoomguy = new Npc("The DoomGuy",doomguyHint,"... (il vous regarde intensément en silence)", "... (il hoche la tête, vous avez raison)","... (il grogne, visiblement agacé)");
		npcs.add(thedoomguy);
		Npc zagreus = new Npc("Zagreus",zagreusHint,"Tiens, un autre mortel venu braver les Enfers ?", "Bravo, c'est bien moi, Zagreus, fils d'Hadès.","Non, pas cette fois. Mais l’échec fait partie du défi.");
		npcs.add(zagreus);
		Npc rayne = new Npc("Rayne",rayneHint,"Attention où tu marches, ou tu pourrais te couper", "Oui, je suis Rayne. Tu aimes jouer avec le feu ?","Non, ce n’est pas moi. Mais tu as du goût pour les ténèbres.");
		npcs.add(rayne);
		Npc kirby = new Npc("Kirby",kirbyHint,"Poyo ! (Il vous regarde en souriant.)", "Poyo ! C’est bien moi, Kirby ! Gagné !","Poyo... (Il fait une moue triste.)");
		npcs.add(kirby);
		Npc link = new Npc("Link",linkHint,"... (Il brandit son épée en guise de salut.)", "... (Il sourit et joue un air sur son ocarina.)","... (Il secoue la tête et pointe vers l’horizon.)");
		npcs.add(link);
		Npc marcusfenix = new Npc("Marcus Fenix",marcusFenixHint,"Tu te crois prêt pour la guerre, rookie ?", "Exact. Marcus Fenix, héros de la CGU, à votre service.","Non, tu t’es trompé de soldat. Essaie encore.");
		npcs.add(marcusfenix);
		Npc blinx = new Npc("Blinx",blinxHint,"Oh, tu veux parler au maître du temps ?", "Exact, c'est moi, Blinx, le chat nettoyeur temporel !","Non, désolé, tu dois rembobiner ta réponse.");
		npcs.add(blinx);
		Npc ori = new Npc("Ori",oriHint,"'Un scintillement lumineux danse autour de vous.'", "'Un doux son résonne, Ori approuve en silence.'","'Un murmure triste traverse la pièce, comme un regret.'");
		npcs.add(ori);
		Npc samusaran = new Npc("Samus Aran",samusAranHint,"La mission n’est pas encore terminée. Tu es prêt ?", "Bien vu. Samus Aran, chasseuse de primes intergalactique.","Non, ton scanner n’est pas bien réglé.");
		npcs.add(samusaran);
		Npc donkeykong = new Npc("Donkey Kong",donkeyKongHint,"Ooh-ooh-ah-ah ! Bienvenue dans ma jungle.", "Haha, ouais, c’est moi, DK ! Passons aux bananes !","Ooh-ooh... Mauvaise réponse. Essaie encore !");
		npcs.add(donkeykong);
		Npc regina = new Npc("Regina",reginaHint,"Attention ! Ce n'est pas un endroit pour les imprudents.", "Bien joué. Regina, experte en situations de crise, à votre service.","Non, ce n'est pas moi. Les dinosaures sont plus rapides que toi ?");
		npcs.add(regina);
		Npc hershelllayton = new Npc("Hershell Layton",hershelLaytonHint,"Une énigme pour toi : qui suis-je ?", "Très juste, je suis le professeur Layton. Félicitations !","Non, ce n’est pas moi. Mais ton raisonnement est proche.");
		npcs.add(hershelllayton);
		Npc samficher = new Npc("Sam Ficher",samFicherHint,"Tu n’entendras pas mes pas, mais je suis là.", "C’est exact. Sam Fisher, agent de l’ombre, à votre service.","Non, mauvaise cible. Réessaie, furtivement cette fois.");
		npcs.add(samficher);
		Npc mario = new Npc("Mario",marioHint,"Bienvenuti, mon ami.", "Ouhouhou, it's me Mario!","Oh no! mamamia!");
		npcs.add(mario);
		Npc alloy = new Npc("Alloy",alloyHint,"Tu as traversé bien des épreuves pour arriver jusqu'ici.", "Tu es perspicace. Moi, c'est Aloy, chasseuse de machines.","Non, ce n'est pas moi. Ton focus doit être reconfiguré");
		npcs.add(alloy);
		Npc vlad = new Npc("Vlad",vladHint,"Cherches-tu la lumière ou les secrets de l’Alchimie ?", "Bien vu. Vlad, adepte de la Psynergie, à ton service.","Non, ton esprit est encore troublé. Réessaye.");
		npcs.add(vlad);
		Npc sacha = new Npc("Sacha",sachaHint,"Je veux devenir le meilleur dresseur, comme personne avant moi.", "Exact ! Sacha Ketchum, de Bourg-Palette ! Prêt pour un duel ?","Non, mauvais Pokémon. Rappelle ton choix et retente ta chance !");
		npcs.add(sacha);
		
		
	    // Rooms creation
	    ArrayList<Room> rooms = new ArrayList<>();
	    Room A0 = new Room("A0",laracroft, null);
	    rooms.add(A0);
	    Room A1 = new Room("A1",null, null);
	    rooms.add(A1);
	    Room A2 = new Room("A2",null, kratosHint);
	    rooms.add(A2);
	    Room A3 = new Room("A3",null, null);
	    rooms.add(A3);
	    Room A4 = new Room("A4",null, spyroHint);
	    rooms.add(A4);
	    Room A5 = new Room("A5",null, null);
	    rooms.add(A5);
	    Room A6 = new Room("A6",null, null);
	    rooms.add(A6);
	    Room A7 = new Room("A7",null, null);
	    rooms.add(A7);
	    Room A8 = new Room("A8",masterchief, crashHint);
	    rooms.add(A8);
	    Room A9 = new Room("A9",null, null);
	    rooms.add(A9);
	    Room B0 = new Room("B0",null, laraCroftHint);
	    rooms.add(B0);
	    Room B1 = new Room("B1",null, null);
	    rooms.add(B1);
	    Room B2 = new Room("B2",cloud, null);
	    rooms.add(B2);
	    Room B3 = new Room("B3",null, reginaHint);
	    rooms.add(B3);
	    Room B4 = new Room("B4",null, null);
	    rooms.add(B4);
	    Room B5 = new Room("B5",geraldderiv, null);
	    rooms.add(B5);
	    Room B6 = new Room("B6",null, alloyHint);
	    rooms.add(B6);
	    Room B7 = new Room("B7",null, null);
	    rooms.add(B7);
	    Room B8 = new Room("B8",null, null);
	    rooms.add(B8);
	    Room B9 = new Room("B9",crashbandicoot, null);
	    rooms.add(B9);
	    Room C0 = new Room("C0",null, null);
	    rooms.add(C0);
	    Room C1 = new Room("C1",kratos, cloudHint);
	    rooms.add(C1);
	    Room C2 = new Room("C2",null, null);
	    rooms.add(C2);
	    Room C3 = new Room("C3",sonic, ellieHint);
	    rooms.add(C3);
	    Room C4 = new Room("C4",null, null);
	    rooms.add(C4);
	    Room C5 = new Room("C5",null, null);
	    rooms.add(C5);
	    Room C6 = new Room("C6",null, null);
	    rooms.add(C6);
	    Room C7 = new Room("C7",madeline, geraldDeRivHint);
	    rooms.add(C7);
	    Room C8 = new Room("C8",null, null);
	    rooms.add(C8);
	    Room C9 = new Room("C9",null, masterChiefHint);
	    rooms.add(C9);
	    Room D0 = new Room("D0",null, rayneHint);
	    rooms.add(D0);
	    Room D1 = new Room("D1",ellie, null);
	    rooms.add(D1);
	    Room D2 = new Room("D2",null, null);
	    rooms.add(D2);
	    Room D4 = new Room("D4",spyro, null);
	    rooms.add(D4);
	    Room D6 = new Room("D6",thedoomguy, null);
	    rooms.add(D6);
	    Room D7 = new Room("D7",null, null);
	    rooms.add(D7);
	    Room D8 = new Room("D8",zagreus, null);
	    rooms.add(D8);
	    Room D9 = new Room("D9",null, null);
	    rooms.add(D9);
	    Room E0 = new Room("E0",rayne, null);
	    rooms.add(E0);
	    Room E1 = new Room("E1",null, blinxHint);
	    rooms.add(E1);
	    Room E2 = new Room("E2",null, sonicHint);
	    rooms.add(E2);
	    Room E3 = new Room("E3",kirby, null);
	    rooms.add(E3);
	    Room E4 = new Room("E4",null, null);
	    rooms.add(E4);
	    Room E5 = new Room("E5",null, null);
	    rooms.add(E5);
	    Room E6 = new Room("E6",null, null);
	    rooms.add(E6);
	    Room E7 = new Room("E7",null, doomguyHint);
	    rooms.add(E7);
	    Room E9 = new Room("E9",link, marcusFenixHint);
	    rooms.add(E9);
	    Room F0 = new Room("F0",null, null);
	    rooms.add(F0);
	    Room F1 = new Room("F1",null, null);
	    rooms.add(F1);
	    Room F2 = new Room("F2",null, null);
	    rooms.add(F2);
	    Room F3 = new Room("F3",null, oriHint);
	    rooms.add(F3);
	    Room F4 = new Room("F4",null, null);
	    rooms.add(F4);
	    Room F5 = new Room("F5",null, madelineHint);
	    rooms.add(F5);
	    Room F6 = new Room("F6",marcusfenix, null);
	    rooms.add(F6);
	    Room F7 = new Room("F7",null, null);
	    rooms.add(F7);
	    Room F8 = new Room("F8",null, zagreusHint);
	    rooms.add(F8);
	    Room F9 = new Room("F9",null, null);
	    rooms.add(F9);
	    Room G0 = new Room("G0",null, null);
	    rooms.add(G0);
	    Room G1 = new Room("G1",blinx, samFicherHint);
	    rooms.add(G1);
	    Room G2 = new Room("G2",ori, null);
	    rooms.add(G2);
	    Room G3 = new Room("G3",null, null);
	    rooms.add(G3);
	    Room G4 = new Room("G4",samusaran, marioHint);
	    rooms.add(G4);
	    Room G5 = new Room("G5",null, null);
	    rooms.add(G5);
	    Room G6 = new Room("G6",null, null);
	    rooms.add(G6);
	    Room G7 = new Room("G7",donkeykong, null);
	    rooms.add(G7);
	    Room G8 = new Room("G8",regina, null);
	    rooms.add(G8);
	    Room G9 = new Room("G9",null, linkHint);
	    rooms.add(G9);
	    Room H0 = new Room("H0",null, null);
	    rooms.add(H0);
	    Room H1 = new Room("H1",null, null);
	    rooms.add(H1);
	    Room H2 = new Room("H2",null, kirbyHint);
	    rooms.add(H2);
	    Room H3 = new Room("H3",null, null);
	    rooms.add(H3);
	    Room H4 = new Room("H4",null, null);
	    rooms.add(H4);
	    Room H5 = new Room("H5",hershelllayton, null);
	    rooms.add(H5);
	    Room H7 = new Room("H7",null, sachaHint);
	    rooms.add(H7);
	    Room H8 = new Room("H8",null, null);
	    rooms.add(H8);
	    Room H9 = new Room("H9",null, null);
	    rooms.add(H9);
	    Room I0 = new Room("I0",samficher, null);
	    rooms.add(I0);
	    Room I1 = new Room("I1",null, null);
	    rooms.add(I1);
	    Room I2 = new Room("I2",null, null);
	    rooms.add(I2);
	    Room I3 = new Room("I3",mario, null);
	    rooms.add(I3);
	    Room I4 = new Room("I4",null, null);
	    rooms.add(I4);
	    Room I5 = new Room("I5",null, samusAranHint);
	    rooms.add(I5);
	    Room I6 = new Room("I6",alloy, null);
	    rooms.add(I6);
	    Room I7 = new Room("I7",null, null);
	    rooms.add(I7);
	    Room I8 = new Room("I8",vlad, null);
	    rooms.add(I8);
	    Room I9 = new Room("I9",null, donkeyKongHint);
	    rooms.add(I9);
	    Room J0 = new Room("J0",null, null);
	    rooms.add(J0);
	    Room J1 = new Room("J1",null, null);
	    rooms.add(J1);
	    Room J2 = new Room("J2",null, null);
	    rooms.add(J2);
	    Room J3 = new Room("J3",null, vladHint);
	    rooms.add(J3);
	    Room J4 = new Room("J4",null, null);
	    rooms.add(J4);
	    Room J5 = new Room("J5",null, null);
	    rooms.add(J5);
	    Room J6 = new Room("J6",null, null);
	    rooms.add(J6);
	    Room J7 = new Room("J7",null, hershelLaytonHint);
	    rooms.add(J7);
	    Room J8 = new Room("J8",null, null);
	    rooms.add(J8);
	    Room J9 = new Room("J9",sacha, null);
	    rooms.add(J9);
	    
	
	    // Link rooms
	    A0.setSouth(A1);
	    A1.setNorth(A0).setSouth(A2);
	    A2.setNorth(A1).setEast(B2).setSouth(A3);
	    A3.setNorth(A2).setSouth(A4);
	    A4.setNorth(A3).setEast(B4);
	    A5.setEast(B5).setSouth(A6);
	    A6.setNorth(A5).setSouth(A7);
	    A7.setNorth(A6).setEast(B7);
	    A8.setSouth(A9);
	    A9.setNorth(A8).setEast(B9);
	    B0.setEast(C0).setSouth(B1);
	    B1.setNorth(B0);
	    B2.setEast(C2).setWest(A2);
	    B3.setEast(C3);
	    B4.setWest(A4);
	    B5.setWest(A5);
	    B6.setEast(C6).setSouth(B7);
	    B7.setNorth(B6).setWest(A7);
	    B8.setSouth(B9);
	    B9.setNorth(B8).setEast(C9).setWest(A9);
	    C0.setEast(D0).setSouth(C1).setWest(B0);
	    C1.setNorth(C0).setSouth(C2);
	    C2.setNorth(C1).setEast(D2).setSouth(C3).setWest(B2);
	    C3.setNorth(C2).setSouth(C4).setWest(B3);
	    C4.setNorth(C3).setEast(D4).setSouth(C5);
	    C5.setNorth(C4).setSouth(C6);
	    C6.setNorth(C5).setWest(B6);
	    C7.setEast(D7).setSouth(C8);
	    C8.setNorth(C7).setEast(D8).setSouth(C9);
	    C9.setNorth(C8).setEast(D9).setWest(B9);
	    D0.setSouth(D1).setWest(C0);
	    D1.setNorth(D0).setEast(E1);
	    D2.setEast(E2).setWest(C2);
	    D4.setEast(E4).setWest(C4);
	    D6.setEast(E6).setSouth(D7);
	    D7.setNorth(D6).setEast(E7).setSouth(D8).setWest(C7);
	    D8.setNorth(D7).setSouth(D9).setWest(C8);
	    D9.setNorth(D8).setWest(C9);
	    E0.setEast(F0);
	    E1.setEast(F1).setWest(D1);
	    E2.setEast(F2).setSouth(E3).setWest(D2);
	    E3.setNorth(E2).setEast(F3);
	    E4.setEast(F4).setSouth(E5).setWest(D4);
	    E5.setNorth(E4).setEast(F5).setSouth(E6);
	    E6.setNorth(E5).setEast(F6).setSouth(E7).setWest(D6);
	    E7.setNorth(E6).setEast(F7).setWest(D7);
	    E9.setEast(F9);
	    F0.setEast(G0).setSouth(F1).setWest(E0);
	    F1.setNorth(F0).setSouth(F2).setWest(E1);
	    F2.setNorth(F1).setSouth(F3).setWest(E2);
	    F3.setNorth(F2).setEast(G3).setWest(E3);
	    F4.setWest(E4);
	    F5.setWest(E5);
	    F6.setEast(G6).setSouth(F7).setWest(E6);
	    F7.setNorth(F6).setWest(E7);
	    F8.setEast(G8);
	    F9.setEast(G9).setWest(E9);
	    G0.setEast(H0).setSouth(G1).setWest(F0);
	    G1.setNorth(G0).setSouth(G2);
	    G2.setNorth(G1).setEast(H2);
	    G3.setEast(H3).setWest(F3);
	    G4.setEast(H4).setSouth(G5);
	    G5.setNorth(G4);
	    G6.setSouth(G7).setWest(F6);
	    G7.setNorth(G6).setEast(H7).setSouth(G8);
	    G8.setNorth(G7).setEast(H8).setSouth(G9).setWest(F8);
	    G9.setNorth(G8).setWest(F9);
	    H0.setSouth(H1).setWest(G0);
	    H1.setNorth(H0).setEast(I1);
	    H2.setEast(I2).setSouth(H3).setWest(G2);
	    H3.setNorth(H2).setSouth(H4).setWest(G3);
	    H4.setNorth(H3).setEast(I4).setSouth(H5).setWest(G4);
	    H5.setNorth(H4).setEast(I5);
	    H7.setEast(I7).setSouth(H8).setWest(G7);
	    H8.setNorth(H7).setEast(I8).setSouth(H9).setWest(G8);
	    H9.setNorth(H8).setEast(I9);
	    I0.setEast(J0);
	    I1.setEast(J1).setWest(H1);
	    I2.setEast(J2).setWest(H2);
	    I3.setEast(J3).setSouth(I4);
	    I4.setNorth(I3).setEast(J4).setWest(H4);
	    I5.setWest(H5);
	    I6.setEast(J6).setSouth(I7);
	    I7.setNorth(I6).setWest(H7);
	    I8.setEast(J8).setWest(H8);
	    I9.setWest(H9);
	    J0.setSouth(J1).setWest(I0);
	    J1.setNorth(J0).setWest(I1);
	    J2.setWest(I2);
	    J3.setSouth(J4).setWest(I3);
	    J4.setNorth(J3).setSouth(J5).setWest(I4);
	    J5.setNorth(J4).setSouth(J6);
	    J6.setNorth(J5).setWest(I6);
	    J7.setSouth(J8);
	    J8.setNorth(J7).setSouth(J9).setWest(I8);
	    J9.setNorth(J8);
	    	

	    //Game creation
	    Game game = new Game("player", F4, npcs.size(), "Labyrinth: Tales of Gamers", "Vous qui êtes en train de lancer ce jeu, préparez-vous à traverser le quatrième mur. Laissez derrière vous le monde réel et entrez dans un labyrinthe où chaque recoin cache un mystère, chaque pièce un défi, et chaque rencontre une énigme. Ici, les règles ne sont dictées que par votre intuition et votre curiosité. Oserez-vous marcher dans l’inconnu, résoudre les indices disséminés dans ce monde pour percer les identités de ceux qui l’habitent ? Alors, franchissez cette porte. Le labyrinthe vous attend, et ses secrets aussi.", "Tout à coup, les lumières s’éteignent. Dans l’ombre, une silhouette se dessine, puis une autre. Un par un, les personnages du labyrinthe entrent dans la pièce, leurs visages illuminés par une lueur reconnaissante. Vous les avez tous trouvés, tous compris. Ils s’inclinent devant vous, un sourire énigmatique aux lèvres, avant de disparaître dans une douce obscurité. Le labyrinthe s’efface, la pièce s'assombrit, et soudain, vous vous réveillez. Votre manette repose dans vos mains, mais quelque chose vous dit que cette aventure n’était pas qu’un simple jeu. Était-ce réel ? Ou seulement une énigme de plus ? À vous de deviner.");
	    for (Room room : rooms) {
	      game.addRoom(room);
	    }
	    //Management de la game
	    game.introduce();
	    while (!game.isTerminated()) {
	      System.out.println("\n--------------------------------------------------\n");
	      game.getPlayer().getCurrentRoom().introduce();
	      game.getPlayer().getCurrentRoom().selectAction();
	    }
	    System.out.println("\n--------------------------------------------------\n");
	    game.terminate();
	  }
	}
